#pragma once

static const char UI_INDEX_HTML[] =
    "<!doctype html><html><head><meta charset=utf-8>"
    "<meta name=viewport content='width=device-width,initial-scale=1'>"
    "<title>HALite</title>"
    "<style>"
    "body{font-family:system-ui,sans-serif;background:#0b0f12;color:#e8eef3;margin:1.2rem}"
    "h1{font-size:1.4rem} .muted{color:#8b9aab;font-size:.85rem}"
    ".row{display:flex;flex-wrap:wrap;gap:.6rem;margin:.8rem 0}"
    "button{border:2px solid #f5d76e;background:transparent;color:#e8eef3;border-radius:8px;"
    "padding:.65rem 1rem;font:500 .9rem system-ui;cursor:pointer}"
    "button.on{background:#f5d76e;color:#1a1608}"
    "button.pj{border-color:#3ecf8e}"
    "</style></head><body>"
    "<h1>HALite</h1>"
    "<p class=muted id=health>Connecting…</p>"
    "<div class=row><button class=pj id=pj>Permit join</button></div>"
    "<div class=row id=grid></div>"
    "<script>"
    "const $=id=>document.getElementById(id);"
    "function btnClass(e){return (e.domain==='switch'&&e.on)?'on':'';}"
    "function render(list){"
    " const g=$('grid'); g.innerHTML='';"
    " (list||[]).forEach(e=>{"
    "  const b=document.createElement('button');"
    "  b.className=btnClass(e);"
    "  b.textContent=e.name+(e.domain==='sensor'?(' '+e.state+' '+(e.unit||'')):(''));"
    "  if(e.domain==='switch'){b.onclick=()=>fetch('/api/entities/'+encodeURIComponent(e.entity_id)+'/command',"
    "    {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle'})});}"
    "  g.appendChild(b);"
    " });"
    "}"
    "async function health(){const r=await fetch('/api/health');const j=await r.json();"
    " $('health').textContent='IPC '+(j.ipc_c6?'up':'down')+' · Wi-Fi '+(j.wifi?'up':'down')+' · MQTT '+(j.mqtt?'up':'down');"
    " const p=await fetch('/api/zigbee/permit_join'); const pj=await p.json();"
    " $('pj').textContent=pj.enabled?'Permit join: ON':'Permit join'; $('pj').className='pj'+(pj.enabled?' on':'');}"
    "async function load(){const r=await fetch('/api/entities'); const j=await r.json(); render(j.entities); health();}"
    "$('pj').onclick=async()=>{const p=await fetch('/api/zigbee/permit_join'); const cur=await p.json();"
    " await fetch('/api/zigbee/permit_join',{method:'POST',headers:{'Content-Type':'application/json'},"
    " body:JSON.stringify({enabled:!cur.enabled})}); load();};"
    "const proto=location.protocol==='https:'?'wss':'ws';"
    "function ws(){const s=new WebSocket(proto+'://'+location.host+'/ws');"
    " s.onmessage=ev=>{const m=JSON.parse(ev.data); if(m.type==='hello') render(m.entities); if(m.type==='state') load();};"
    " s.onclose=()=>setTimeout(ws,2000);} load(); ws(); setInterval(load,3000);"
    "</script></body></html>";
